<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Thu, 22 Feb 2024 21:08:39 -0300
 */

$conf['title'] = '';
$conf['start'] = '';
$conf['lang'] = 'pt-br';
$conf['license'] = 'gnufdl';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['updatecheck'] = 0;
$conf['tpl']['argon']['hideTools'] = '1';
$conf['tpl']['argon']['movePageTools'] = '1';
$conf['tpl']['argon']['showIcon'] = '1';
