name: Debug changes

on: 
  workflow_call:
    inputs:
      digest:
        required: false
        type: string
        default: 'none'

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run steps
        run: echo "${{ inputs.digest }}"
