name: Debug changes

on: 
  workflow_call:
    inputs:
      digest:
        required: false
        type: string
        default: 'none'

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run steps
        run: |
          echo "Digest = ${{ inputs.digest }}"
          echo "Version = $(grep '^## v' | head -n1 | cut -d' ' -f2)"
          echo "Body = $(tail -n +3 release_notes)"
