name: Debug changes

on: 
  workflow_call:
    inputs:
      changed:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Show input value
        run: echo "Changed => ${{ inputs.changed }}"
