name: Build/Scan/Test/Push/Release

on:
  push:
    branches: [ 'main' ]
    paths:
      - '.github/workflows/**'
      - 'app/**'
      - 'docker/**'
      - 'tests/**'

concurrency:
  group: cd-main
  cancel-in-progress: false
  
jobs:
  build:
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
  
  scan:
    needs: build
    uses: ./.github/workflows/scan.yaml
    with:
      image: ${{ github.event.repository.name }}:${{ needs.build.outputs.tag }}
      artifact_name: ${{ needs.build.outputs.artifact }}
    permissions:
      contents: read

  test:
    needs: [ build, scan ]
    uses: ./.github/workflows/test.yaml
    with:
      image: ${{ github.event.repository.name }}:${{ needs.build.outputs.tag }}
      artifact_name: ${{ needs.build.outputs.artifact }}
    permissions:
      contents: read

  push:
    needs: [ build, test ]
    uses: ./.github/workflows/push.yaml
    with:
      tag: ${{ needs.build.outputs.tag }}
      artifact_name: ${{ needs.build.outputs.artifact }}
    permissions:
      contents: read
      packages: write
  
  release:
    needs: push
    uses: ./.github/workflows/release.yaml
    permissions:
      contents: write
