name: Release

on:
  workflow_call:
    inputs:
      digest:
        type: string
        default: ''

jobs:
  exists:
    runs-on: ubuntu-latest

    outputs:
      release: ${{ steps.release.outputs.tag }}
      check: ${{ steps.check.outputs.exists }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v6.1.0

      - name: Get version for release tag
        id: release
        run: echo "tag=$(grep "^# v" release_notes | head -n1 | cut -d' ' -f2)" >> "$GITHUB_OUTPUT"

      - name: Check if release already exists
        id: check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.release.outputs.tag }}
        run: |
          if gh release view "$TAG" >/dev/null 2>&1; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          fi

  launch:
    needs: exists
    if: needs.exists.outputs.check != 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6.1.0

      - name: Prepare body file to release release_notes
        run: tail -n +3 release_notes > /tmp/body.md
      
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v4.4.1

      - name: Get image digest
        id: digest
        run: |
          if ${{ inputs.digest }} != ''; then
            echo "manifest=${{ inputs.digest }}" >> "$GITHUB_OUTPUT"
          else
            IMG_TAG=$(cut -d' ' -f1 app/VERSION)
            IMG="ghcr.io/mafpbiaggi/dokuwiki:$IMG_TAG"
            MANIFEST=$(docker buildx imagetools inspect $IMG --format '{{ .Manifest }}' | grep -v 'MediaType')
            echo "manifest=$MANIFEST" >> "GITHUB_OUTPUT"
          fi

      - name: Add digest to body file
        env:
          DIGEST: ${{ steps.digest.outputs.manifest }}
        run: |
          echo -e "\n## Imagem" >> /tmp/body.md
          echo "\`\`\`text" >> /tmp/body.md
          echo "$DIGEST" >> /tmp/body.md
          echo "\`\`\`text" >> /tmp/body.md

      - name: Create Release
        uses: ncipollo/release-action@v1.21.0
        env:
          RELEASE_TAG: ${{ needs.exists.outputs.release }}
        with:
          tag: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
          bodyFile: /tmp/body.md
          commit: ${{ github.sha }}
