name: Scan

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      artifact_name:
        required: true
        type: string

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: ${{ inputs.artifact_name }}
          path: /tmp/image

      - name: Load image from artifact
        run: docker load -i /tmp/image/image.tar

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: '${{ inputs.image }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
