name: Integration tests

on:
  workflow_run:
    workflows: ["Docker build environment"]
    types:
      - completed
  
  pull_request: 
    branches: [ '*' ]
    paths:
      - '.github/workflows/tests.yaml'
      - 'tests/**'

jobs:
  tests:
    if: ${{ github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name:  Check out repository
        uses: actions/checkout@v6.1.0
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.event.pull_request.head.sha }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image and start container
        run: |
          WORKDIR=$(pwd)
          IMAGE="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$(cut -d' ' -f1 ${WORKDIR}/app/VERSION)"
          PERSISTENT_CONF1="${WORKDIR}/tests/conf/local.php:/var/www/html/conf/local.php"
          PERSISTENT_CONF2="${WORKDIR}/tests/conf/acl.auth.php:/var/www/html/conf/acl.auth.php"
          PERSISTENT_CONF3="${WORKDIR}/tests/conf/users.auth.php:/var/www/html/conf/users.auth.php"
          docker pull ${IMAGE}
          docker run -d \
            --name ${{ github.event.repository.name }} \
            -p 80:80 \
            -v ${PERSISTENT_CONF1} \
            -v ${PERSISTENT_CONF2} \
            -v ${PERSISTENT_CONF3} \
            ${IMAGE}

      - name: Wait for container readiness
        run: |
          echo "Waiting for container readiness ..."
          sleep 10
      
      - name: Verify container status
        run: |
          bash tests/container_status.sh ${{ github.event.repository.name }}

      - name: Check application health
        run: |
          bash tests/health_check_app.sh

      - name: Clean up temporary resources
        if: always()
        run: docker rm -f ${{ github.event.repository.name }} || true
