name: Integration tests

on:
  workflow_run:
    workflows: ["Docker build environment"]
    types:
      - completed

jobs:
  tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v6.1.0
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Log in to GitHub container registry
        uses: docker/login-action@v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image and run container
        run: |
          IMAGE_TAG=$(cut -d' ' -f1 app/VERSION)
          PERSISTENT_DATA="tests/data:/var/www/html/data"
          PERSISTENT_CONF1="tests/conf/local.php:/var/www/html/conf/local.php"
          PERSISTENT_CONF2="tests/conf/acl.auth.php:/var/www/html/conf/acl.auth.php"
          PERSISTENT_CONF3="tests/conf/users.auth.php:/var/www/html/conf/users.auth.php"
          docker pull ghcr.io/${{ github.repository_owner }}/dokuwiki:$IMAGE_TAG
          docker run -d \
            --name dokuwiki_test \
            -p 80:80 \
            -v ${PERSISTENT_DATA} \
            -v ${PERSISTENT_CONF1} \
            -v ${PERSISTENT_CONF2} \
            -v ${PERSISTENT_CONF3} \
            ghcr.io/${{ github.repository_owner }}/dokuwiki:$IMAGE_TAG

      - name: Wait for container to be running
        run: |
          echo "Waiting for container to be running..."
          sleep 10
      
      - name: Check container status
        run: |
          STATUS=$(docker inspect --format='{{ .State.Status }}' dokuwiki_test)
          echo "Status: $STATUS"
          if [ "$STATUS" != "running" ]; then
            echo "Error: Container dokuwiki_test is not running."
            docker logs dokuwiki_test
            exit 1
          fi
          echo "Container dokuwiki_test is running."
      
      - name: Run test
        run: |
          bash tests/check.sh

      - name: Cleanup
        if: always()
        run: docker rm -f dokuwiki_test || true
